//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2/15/2011 3:52:31 PM
namespace AzureDataMarketExample.UnitedNationsData
{
    
    /// <summary>
    /// There are no comments for UnitedNationsNationalAccountsContainer in the schema.
    /// </summary>
    public partial class UnitedNationsNationalAccountsContainer : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new UnitedNationsNationalAccountsContainer object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public UnitedNationsNationalAccountsContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("UnitedNations.NationalAccounts", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("AzureDataMarketExample.UnitedNationsData", typeName.Substring(30)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("AzureDataMarketExample.UnitedNationsData", global::System.StringComparison.Ordinal))
            {
                return string.Concat("UnitedNations.NationalAccounts.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for DataSeries in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DataSeries> DataSeries
        {
            get
            {
                if ((this._DataSeries == null))
                {
                    this._DataSeries = base.CreateQuery<DataSeries>("DataSeries");
                }
                return this._DataSeries;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DataSeries> _DataSeries;
        /// <summary>
        /// There are no comments for Footnotes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Footnotes> Footnotes
        {
            get
            {
                if ((this._Footnotes == null))
                {
                    this._Footnotes = base.CreateQuery<Footnotes>("Footnotes");
                }
                return this._Footnotes;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Footnotes> _Footnotes;
        /// <summary>
        /// There are no comments for Values in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Values> Values
        {
            get
            {
                if ((this._Values == null))
                {
                    this._Values = base.CreateQuery<Values>("Values");
                }
                return this._Values;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Values> _Values;
        /// <summary>
        /// There are no comments for DataSeries in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDataSeries(DataSeries dataSeries)
        {
            base.AddObject("DataSeries", dataSeries);
        }
        /// <summary>
        /// There are no comments for Footnotes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFootnotes(Footnotes footnotes)
        {
            base.AddObject("Footnotes", footnotes);
        }
        /// <summary>
        /// There are no comments for Values in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToValues(Values values)
        {
            base.AddObject("Values", values);
        }
    }
    /// <summary>
    /// There are no comments for UnitedNations.NationalAccounts.DataSeries in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DataSeries")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class DataSeries : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DataSeries object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DataSeries CreateDataSeries(string ID)
        {
            DataSeries dataSeries = new DataSeries();
            dataSeries.Id = ID;
            return dataSeries;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property DataSetId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DataSetId
        {
            get
            {
                return this._DataSetId;
            }
            set
            {
                this.OnDataSetIdChanging(value);
                this._DataSetId = value;
                this.OnDataSetIdChanged();
                this.OnPropertyChanged("DataSetId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DataSetId;
        partial void OnDataSetIdChanging(string value);
        partial void OnDataSetIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for UnitedNations.NationalAccounts.Footnotes in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UniqueId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Footnotes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("UniqueId")]
    public partial class Footnotes : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Footnotes object.
        /// </summary>
        /// <param name="uniqueId">Initial value of UniqueId.</param>
        /// <param name="sequenceId">Initial value of SequenceId.</param>
        /// <param name="ID">Initial value of Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Footnotes CreateFootnotes(string uniqueId, short sequenceId, int ID)
        {
            Footnotes footnotes = new Footnotes();
            footnotes.UniqueId = uniqueId;
            footnotes.SequenceId = sequenceId;
            footnotes.Id = ID;
            return footnotes;
        }
        /// <summary>
        /// There are no comments for Property UniqueId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UniqueId
        {
            get
            {
                return this._UniqueId;
            }
            set
            {
                this.OnUniqueIdChanging(value);
                this._UniqueId = value;
                this.OnUniqueIdChanged();
                this.OnPropertyChanged("UniqueId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UniqueId;
        partial void OnUniqueIdChanging(string value);
        partial void OnUniqueIdChanged();
        /// <summary>
        /// There are no comments for Property SequenceId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short SequenceId
        {
            get
            {
                return this._SequenceId;
            }
            set
            {
                this.OnSequenceIdChanging(value);
                this._SequenceId = value;
                this.OnSequenceIdChanged();
                this.OnPropertyChanged("SequenceId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _SequenceId;
        partial void OnSequenceIdChanging(short value);
        partial void OnSequenceIdChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Text in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Text
        {
            get
            {
                return this._Text;
            }
            set
            {
                this.OnTextChanging(value);
                this._Text = value;
                this.OnTextChanged();
                this.OnPropertyChanged("Text");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Text;
        partial void OnTextChanging(string value);
        partial void OnTextChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for UnitedNations.NationalAccounts.Values in the schema.
    /// </summary>
    /// <KeyProperties>
    /// BaseYear
    /// CountryCode
    /// DataSeriesId
    /// FiscalYear
    /// ItemCode
    /// Series
    /// SNA93ItemCode
    /// SNA93TableCode
    /// SNASystem
    /// SubItemCode
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Values")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("BaseYear", "CountryCode", "DataSeriesId", "FiscalYear", "ItemCode", "Series", "SNA93ItemCode", "SNA93TableCode", "SNASystem", "SubItemCode")]
    public partial class Values : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Values object.
        /// </summary>
        /// <param name="dataSeriesId">Initial value of DataSeriesId.</param>
        /// <param name="countryCode">Initial value of CountryCode.</param>
        /// <param name="sNA93TableCode">Initial value of SNA93TableCode.</param>
        /// <param name="itemCode">Initial value of ItemCode.</param>
        /// <param name="sNA93ItemCode">Initial value of SNA93ItemCode.</param>
        /// <param name="fiscalYear">Initial value of FiscalYear.</param>
        /// <param name="series">Initial value of Series.</param>
        /// <param name="sNASystem">Initial value of SNASystem.</param>
        /// <param name="baseYear">Initial value of BaseYear.</param>
        /// <param name="subItemCode">Initial value of SubItemCode.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Values CreateValues(string dataSeriesId, short countryCode, double sNA93TableCode, short itemCode, string sNA93ItemCode, short fiscalYear, short series, byte sNASystem, short baseYear, short subItemCode)
        {
            Values values = new Values();
            values.DataSeriesId = dataSeriesId;
            values.CountryCode = countryCode;
            values.SNA93TableCode = sNA93TableCode;
            values.ItemCode = itemCode;
            values.SNA93ItemCode = sNA93ItemCode;
            values.FiscalYear = fiscalYear;
            values.Series = series;
            values.SNASystem = sNASystem;
            values.BaseYear = baseYear;
            values.SubItemCode = subItemCode;
            return values;
        }
        /// <summary>
        /// There are no comments for Property DataSeriesId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DataSeriesId
        {
            get
            {
                return this._DataSeriesId;
            }
            set
            {
                this.OnDataSeriesIdChanging(value);
                this._DataSeriesId = value;
                this.OnDataSeriesIdChanged();
                this.OnPropertyChanged("DataSeriesId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DataSeriesId;
        partial void OnDataSeriesIdChanging(string value);
        partial void OnDataSeriesIdChanged();
        /// <summary>
        /// There are no comments for Property CountryCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short CountryCode
        {
            get
            {
                return this._CountryCode;
            }
            set
            {
                this.OnCountryCodeChanging(value);
                this._CountryCode = value;
                this.OnCountryCodeChanged();
                this.OnPropertyChanged("CountryCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _CountryCode;
        partial void OnCountryCodeChanging(short value);
        partial void OnCountryCodeChanged();
        /// <summary>
        /// There are no comments for Property CountryName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CountryName
        {
            get
            {
                return this._CountryName;
            }
            set
            {
                this.OnCountryNameChanging(value);
                this._CountryName = value;
                this.OnCountryNameChanged();
                this.OnPropertyChanged("CountryName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CountryName;
        partial void OnCountryNameChanging(string value);
        partial void OnCountryNameChanged();
        /// <summary>
        /// There are no comments for Property SNA93TableCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double SNA93TableCode
        {
            get
            {
                return this._SNA93TableCode;
            }
            set
            {
                this.OnSNA93TableCodeChanging(value);
                this._SNA93TableCode = value;
                this.OnSNA93TableCodeChanged();
                this.OnPropertyChanged("SNA93TableCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _SNA93TableCode;
        partial void OnSNA93TableCodeChanging(double value);
        partial void OnSNA93TableCodeChanged();
        /// <summary>
        /// There are no comments for Property SubGroup in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SubGroup
        {
            get
            {
                return this._SubGroup;
            }
            set
            {
                this.OnSubGroupChanging(value);
                this._SubGroup = value;
                this.OnSubGroupChanged();
                this.OnPropertyChanged("SubGroup");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SubGroup;
        partial void OnSubGroupChanging(string value);
        partial void OnSubGroupChanged();
        /// <summary>
        /// There are no comments for Property ItemCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short ItemCode
        {
            get
            {
                return this._ItemCode;
            }
            set
            {
                this.OnItemCodeChanging(value);
                this._ItemCode = value;
                this.OnItemCodeChanged();
                this.OnPropertyChanged("ItemCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _ItemCode;
        partial void OnItemCodeChanging(short value);
        partial void OnItemCodeChanged();
        /// <summary>
        /// There are no comments for Property Item in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Item
        {
            get
            {
                return this._Item;
            }
            set
            {
                this.OnItemChanging(value);
                this._Item = value;
                this.OnItemChanged();
                this.OnPropertyChanged("Item");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Item;
        partial void OnItemChanging(string value);
        partial void OnItemChanged();
        /// <summary>
        /// There are no comments for Property SNA93ItemCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SNA93ItemCode
        {
            get
            {
                return this._SNA93ItemCode;
            }
            set
            {
                this.OnSNA93ItemCodeChanging(value);
                this._SNA93ItemCode = value;
                this.OnSNA93ItemCodeChanged();
                this.OnPropertyChanged("SNA93ItemCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SNA93ItemCode;
        partial void OnSNA93ItemCodeChanging(string value);
        partial void OnSNA93ItemCodeChanged();
        /// <summary>
        /// There are no comments for Property FiscalYear in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short FiscalYear
        {
            get
            {
                return this._FiscalYear;
            }
            set
            {
                this.OnFiscalYearChanging(value);
                this._FiscalYear = value;
                this.OnFiscalYearChanged();
                this.OnPropertyChanged("FiscalYear");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _FiscalYear;
        partial void OnFiscalYearChanging(short value);
        partial void OnFiscalYearChanged();
        /// <summary>
        /// There are no comments for Property Series in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short Series
        {
            get
            {
                return this._Series;
            }
            set
            {
                this.OnSeriesChanging(value);
                this._Series = value;
                this.OnSeriesChanged();
                this.OnPropertyChanged("Series");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _Series;
        partial void OnSeriesChanging(short value);
        partial void OnSeriesChanged();
        /// <summary>
        /// There are no comments for Property Currency in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Currency
        {
            get
            {
                return this._Currency;
            }
            set
            {
                this.OnCurrencyChanging(value);
                this._Currency = value;
                this.OnCurrencyChanged();
                this.OnPropertyChanged("Currency");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Currency;
        partial void OnCurrencyChanging(string value);
        partial void OnCurrencyChanged();
        /// <summary>
        /// There are no comments for Property SNASystem in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte SNASystem
        {
            get
            {
                return this._SNASystem;
            }
            set
            {
                this.OnSNASystemChanging(value);
                this._SNASystem = value;
                this.OnSNASystemChanged();
                this.OnPropertyChanged("SNASystem");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte _SNASystem;
        partial void OnSNASystemChanging(byte value);
        partial void OnSNASystemChanged();
        /// <summary>
        /// There are no comments for Property FiscalYearType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FiscalYearType
        {
            get
            {
                return this._FiscalYearType;
            }
            set
            {
                this.OnFiscalYearTypeChanging(value);
                this._FiscalYearType = value;
                this.OnFiscalYearTypeChanged();
                this.OnPropertyChanged("FiscalYearType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FiscalYearType;
        partial void OnFiscalYearTypeChanging(string value);
        partial void OnFiscalYearTypeChanged();
        /// <summary>
        /// There are no comments for Property BaseYear in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short BaseYear
        {
            get
            {
                return this._BaseYear;
            }
            set
            {
                this.OnBaseYearChanging(value);
                this._BaseYear = value;
                this.OnBaseYearChanged();
                this.OnPropertyChanged("BaseYear");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _BaseYear;
        partial void OnBaseYearChanging(short value);
        partial void OnBaseYearChanged();
        /// <summary>
        /// There are no comments for Property SubItemCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short SubItemCode
        {
            get
            {
                return this._SubItemCode;
            }
            set
            {
                this.OnSubItemCodeChanging(value);
                this._SubItemCode = value;
                this.OnSubItemCodeChanged();
                this.OnPropertyChanged("SubItemCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _SubItemCode;
        partial void OnSubItemCodeChanging(short value);
        partial void OnSubItemCodeChanged();
        /// <summary>
        /// There are no comments for Property sub_item_english_name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<short> sub_item_english_name
        {
            get
            {
                return this._sub_item_english_name;
            }
            set
            {
                this.Onsub_item_english_nameChanging(value);
                this._sub_item_english_name = value;
                this.Onsub_item_english_nameChanged();
                this.OnPropertyChanged("sub_item_english_name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<short> _sub_item_english_name;
        partial void Onsub_item_english_nameChanging(global::System.Nullable<short> value);
        partial void Onsub_item_english_nameChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<float> Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<float> _Value;
        partial void OnValueChanging(global::System.Nullable<float> value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property FootnoteSequenceId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FootnoteSequenceId
        {
            get
            {
                return this._FootnoteSequenceId;
            }
            set
            {
                this.OnFootnoteSequenceIdChanging(value);
                this._FootnoteSequenceId = value;
                this.OnFootnoteSequenceIdChanged();
                this.OnPropertyChanged("FootnoteSequenceId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FootnoteSequenceId;
        partial void OnFootnoteSequenceIdChanging(string value);
        partial void OnFootnoteSequenceIdChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
